const LocalImages = {
  ospreyQRLogo: require('../../assets/images/OspreyQRLogo.png'),
  india: require('../../assets/images/india.png'),
  arrowDown: require('../../assets/images/Chevron_Bottom.png'),
  cross: require('../../assets/images/crossIcon.png'),
  eyeOpen: require('../../assets/images/EyeIcon.png'),
  eyeClosed: require('../../assets/images/eyeClosed.png'),
  otpBox: require('../../assets/images/otp_box.png'),
  greyCross: require('../../assets/images/Cancel_job_icon.png'),
  clockIcon: require('../../assets/images/ClockIcon.png'),
  arrowLeft: require('../../assets/images/arrow-left(non-optimized).png'),
  checkIcon: require('../../assets/images/check_icon.png'),
  arrowRight: require('../../assets/images/arrow-right(non-optimized).png'),
  emptyBox: require('../../assets/images/CheckBox_Uncheck1.png'),
  tickedBox: require('../../assets/images/checkedCheckbox.png'),
  delete: require('../../assets/images/Delete.png'),
  early: require('../../assets/images/early.png'),
  anyTimeSelected: require('../../assets/images/any.png'),
  dayIcon: require('../../assets/images/day.png'),
  nightIcon: require('../../assets/images/night.png'),
  editIcon: require('../../assets/images/otp_pencil.png'),
  uploadIcon: require('../../assets/images/uploadIcon.png'),
  resume: require('../../assets/images/resume.png'),
  calender: require('../../assets/images/Calendar_icon1.png'),
  emptyCardboardBox: require('../../assets/images/box.png'),
  defaultImagePicker:
    'https://w7.pngwing.com/pngs/419/473/png-transparent-computer-icons-user-profile-login-user-heroes-sphere-black-thumbnail.png',
};

export default LocalImages;
