const Strings = {
  one: '1',
  two: '2',
  three: '3',
  astrick: ' *',
  Two: '2',
  Three: '3',
  done: 'Done',
  skip: 'Skip',
  saved: 'Saved',
  email: 'Email',
  Close: 'Close',
  Login: 'Login',
  Name: 'Pivvot',
  '4AM+': '4 AM+',
  '8AM+': '8 AM+',
  '6PM+': '6 PM+',
  Skills: 'Skills',
  Resume: 'Resume',
  submit: 'Submit',
  Search: 'Search',
  gender: 'Gender',
  proceed: 'Proceed',
  address: 'Address',
  country: 'Country',
  zipcode: 'Zipcode',
  location: 'Location',
  dob: 'Date of birth',
  allDay: 'All Day',
  resume: '• Resume',
  jobRoles: 'Job Role',
  Continue: 'Continue',
  Password: 'Password',
  Language: 'Language',
  password: 'Password',
  cityName: 'City name',
  phone: 'Phone Number',
  dayShift: 'Day Shift',
  anyShift: 'Any Shift',
  lastName: 'Last name',
  basicInfo: 'Basic info',
  Languages: 'Languages',
  language: '• Language',
  singapore: 'Singapore',
  firstName: 'First name',
  proficiency: 'Proficiency',
  optional: ' (optional)',
  addResume: 'Add Resume',
  otherInfo: 'Other info',
  Submit_OTP: 'Submit OTP',
  nationality: 'Nationality',
  middleName: 'Middle name',
  nightShift: 'Night Shift',
  earlyShift: 'Early Shift',
  chooseRole: 'Choose role',
  addLanguage: 'Add Language',
  jobRole: 'Current job role',
  Resend_Code: 'Resend Code',
  jobEndDate: 'Job end date',
  signUp: 'Signup & register',
  Phone_Number: 'Phone Number',
  selectSkills: 'Select skills',
  jobStartDate: 'Job start date',
  PasswordHeader: 'Welcome back',
  enterJobRole: 'Enter Job Role',
  Verify_Number: 'Verify Number',
  signUpEmail: 'Enter your email',
  streetAddress: 'Street address',
  stepOne: '• Step 1 : Basic Info',
  privacyPolicy: ' Privacy Policy',
  Password_Input: 'Enter Password',
  certification: '• Certification',
  Certifications: 'Certifications',
  forgotPassword: 'Forgot Password',
  LoginHeader: 'Welcome to Pivvot,',
  workExperience: 'Work experience',
  timePreference: 'Time Preference',
  Add_Job_Roles: '+ Add job roles ',
  numberOfYears: 'Number of year(s)',
  selectLocation: 'Select locations',
  saveAndContinue: 'Save & continue',
  selectJobRoles: 'Select job roles',
  identification: '• Identification',
  Job_Preferences: 'Job Preferences',
  notUploadedYet: 'Not uploaded yet',
  selectlocations: 'Select locations',
  numberOfMonths: 'Number of month(s)',
  exploreJobsNow: 'Explore jobs now ?',
  signUpPassword: 'Enter your password',
  singUpLastName: 'Enter your last name',
  skipAndExplore: 'Skip & explore jobs',
  enterDescription: 'Enter description',
  stepTwo: '• Step 2 : Job Preferences',
  selectProficiency: 'SelectProficiency',
  resumeExperience: 'Resume & experience',
  signUpFirstName: 'Enter your first name',
  experienceDetails: 'Experience Details',
  Phone_Number_Input: 'Enter Phone Number',
  completeProfileButton: 'Complete profile',
  signUpMiddleName: 'Enter your middle name',
  termsAndCondition: 'Terms and Conditions',
  selectDateAndMonth: 'Select date & month',
  breifAboutThisRole: 'Breif about this role',
  OTP_Sent: 'We have sent a four digit OTP to',
  aboutYourSelf: 'Please tell us about yourself',
  incorrectEmail: 'Incorrect email, please retry',
  picker: 'Warehouse Operations - Picker / Packer',
  Know_Your_Job_Preferences: 'Please let us know your preferences for your job',
  Add_Prefered_Job_Category:
    'Please add your preferred job category along with their respective roles.',
  Add_Skills:
    'Add some of your skills to the profile in order to get the opportunities accordingly.',
  Know_Skills: 'Please let us know about your skills',
  provideLocationPreferennce:
    'Please provide location preferences and time preferences.',
  addTimePreferences: '+ Add time preferences ',
  selectTimePreference: 'Select time preferences',
  setUpProfileAs: 'I want to setup my profile as a',
  incorrectName: 'Name should be in correct format',
  addWorkExperience: '+ Add work experience details',
  tapToUploadYourResume: 'Tap to upload your resume',
  stepThree: '• Step 3 : Credentials and other info',
  stillInThisEmployement: 'Still in this employement',
  LoginSubHeader: 'Enter mobile number to get started',
  signUpOsprey: 'Signup and register yourself on OSPREY',
  forkliftDriver: 'Warehouse Operations - Forklift Driver',
  deliveryDriver: 'Warehouse Operations - Delivery Driver',
  completeProfile: 'Complete your profile in just few steps',
  warehouseAssistent: 'Warehouse Operations - Warehouse Assistant',
  administrativeAssistant: 'Administrative - Administrative Assistant',
  timePreferenceSubHeader:
    'Please select shift preferences as per your comfort',
  PasswordSubHeader: 'Enter your password to login into your account',
  OTP_Header: 'Please enter OTP in order to verify your mobile number',
  customerServiceAssistant: 'Customer Service - Customer Service Assistant',
  frontDeskAssistant: 'Customer Service - Receptionist / Front Desk Assistant',
  fileSizeMaxFormatPDFDoc: 'File size : 500kb max., format PDF, Doc.',
  requirementsToBuildYourProfile: 'Requirements to build your profile',
  creatingAccount: 'By creating an account, you have read and agreed to our ',
  succesfullyCreatedAccount:
    'You have successfully created your account with OSPREY',
  settingUpProfile:
    'Choose your role for setting up your profile on the application',
  tellUsYourSelf:
    'Please tell us about yourself. This step is required to explore jobs',
  prefrenceForJob:
    'Please let us know your preferences for jobs. This step required to explore jobs',
  incorrectPassword:
    'Password must contain minimum 8 characters, one uppercase, lowercase, number and a special character.',
  identifyDocuments:
    'Please provide the identity documents and other info. This step is optional to explore jobs but required to apply to jobs',
  congratulationLines:
    'Congratulations! You have completed the first 2 stages of your Profile Setup. Now you can start exploring jobs. ',
  youCanComplete:
    'You can complete the final stage at a later time before you apply to jobs. ',
};

export default Strings;
