export const countryCodes = [
  {
    name: {
      en: 'Afghanistan',
      ru: 'Афганистан',
      pl: 'Afganistan',
      ua: 'Афганістан',
      cz: 'Afghánistán',
      by: '',
      pt: 'Afeganistão',
      es: 'Afganistán',
    },
    dial_code: '+93',
    code: 'AF',
    flag: '🇦🇫',
  },
  {
    name: {
      en: 'Albania',
      ru: 'Албания',
      pl: 'Albania',
      ua: 'Албанія',
      cz: 'Albánie',
      by: '',
      pt: 'Albânia',
      es: 'Albania',
    },
    dial_code: '+355',
    code: 'AL',
    flag: '🇦🇱',
  },
  {
    name: {
      en: 'Antarctica',
      ru: 'Антарктида',
      pl: 'Antarktyda',
      ua: 'Антарктида',
      cz: 'Antarktida',
      by: '',
      pt: 'Antarctica',
      es: 'Antártida',
    },
    dial_code: '+672',
    code: 'AQ',
    flag: '🇦🇶',
  },
  {
    name: {
      en: 'Argentina',
      ru: 'Аргентина',
      pl: 'Argentyna',
      ua: 'Аргентина',
      cz: 'Argentina',
      by: '',
      pt: 'Argentina',
      es: 'Argentina',
    },
    dial_code: '+54',
    code: 'AR',
    flag: '🇦🇷',
  },
  {
    name: {
      en: 'Australia',
      ru: 'Австралия',
      pl: 'Australia',
      ua: 'Австралія',
      cz: 'Austrálie',
      by: '',
      pt: 'Austrália',
      es: 'Australia',
    },
    dial_code: '+61',
    code: 'AU',
    flag: '🇦🇺',
  },
  {
    name: {
      en: 'Austria',
      ru: 'Австрия',
      pl: 'Austria',
      ua: 'Австрія',
      cz: 'Rakousko',
      by: '',
      pt: 'Áustria',
      es: 'Austria',
    },
    dial_code: '+43',
    code: 'AT',
    flag: '🇦🇹',
  },
  {
    name: {
      en: 'Azerbaijan',
      ru: 'Азербайджан',
      pl: 'Azerbejdżan',
      ua: 'Азербайджан',
      cz: 'Ázerbajdžán',
      by: '',
      pt: 'Azerbaijão',
      es: 'Azerbaiyán',
    },
    dial_code: '+994',
    code: 'AZ',
    flag: '🇦🇿',
  },
  {
    name: {
      en: 'Bahamas',
      ru: 'Багамские Острова',
      pl: 'Bahamy',
      ua: 'Багамські острови',
      cz: 'Bahamy',
      by: '',
      pt: 'Baamas',
      es: 'Bahamas',
    },
    dial_code: '+1242',
    code: 'BS',
    flag: '🇧🇸',
  },
  {
    name: {
      en: 'Bahrain',
      ru: 'Бахрейн',
      pl: 'Bahrajn',
      ua: 'Бахрейн',
      cz: 'Bahrajn',
      by: '',
      pt: 'Barém',
      es: 'Bahrein',
    },
    dial_code: '+973',
    code: 'BH',
    flag: '🇧🇭',
  },
  {
    name: {
      en: 'Bangladesh',
      ru: 'Бангладеш',
      pl: 'Bangladesz',
      ua: 'Бангладеш',
      cz: 'Bangladéš',
      by: '',
      pt: 'Bangladeche',
      es: 'Bangladesh',
    },
    dial_code: '+880',
    code: 'BD',
    flag: '🇧🇩',
  },
  {
    name: {
      en: 'Belgium',
      ru: 'Бельгия',
      pl: 'Belgia',
      ua: 'Бельгія',
      cz: 'Belgie',
      by: '',
      pt: 'Bélgica',
      es: 'Bélgica',
    },
    dial_code: '+32',
    code: 'BE',
    flag: '🇧🇪',
  },
  {
    name: {
      en: 'Bermuda',
      ru: 'Бермуды',
      pl: 'Bermudy',
      ua: 'Бермуди',
      cz: 'Bermudy',
      by: '',
      pt: 'Bermudas',
      es: 'Bermudas',
    },
    dial_code: '+1441',
    code: 'BM',
    flag: '🇧🇲',
  },
  {
    name: {
      en: 'Bhutan',
      ru: 'Бутан',
      pl: 'Bhutan',
      ua: 'Бутан',
      cz: 'Bhútán',
      by: '',
      pt: 'Butão',
      es: 'Bután',
    },
    dial_code: '+975',
    code: 'BT',
    flag: '🇧🇹',
  },
  {
    name: {
      en: 'Brazil',
      ru: 'Бразилия',
      pl: 'Brazylia',
      ua: 'Бразилія',
      cz: 'Brazílie',
      by: '',
      pt: 'Brasil',
      es: 'Brasil',
    },
    dial_code: '+55',
    code: 'BR',
    flag: '🇧🇷',
  },
  {
    name: {
      en: 'Bulgaria',
      ru: 'Болгария',
      pl: 'Bułgaria',
      ua: 'Болгарія',
      cz: 'Bulharsko',
      by: '',
      pt: 'Bulgária',
      es: 'Bulgaria',
    },
    dial_code: '+359',
    code: 'BG',
    flag: '🇧🇬',
  },
  {
    name: {
      en: 'Cambodia',
      ru: 'Камбоджа',
      pl: 'Kambodża',
      ua: 'Камбоджа',
      cz: 'Kambodža',
      by: '',
      pt: 'Camboja',
      es: 'Camboya',
    },
    dial_code: '+855',
    code: 'KH',
    flag: '🇰🇭',
  },
  {
    name: {
      en: 'Cameroon',
      ru: 'Камерун',
      pl: 'Kamerun',
      ua: 'Камерун',
      cz: 'Kamerun',
      by: '',
      pt: 'Camarões',
      es: 'Camerún',
    },
    dial_code: '+237',
    code: 'CM',
    flag: '🇨🇲',
  },
  {
    name: {
      en: 'Canada',
      ru: 'Канада',
      pl: 'Kanada',
      ua: 'Канада',
      cz: 'Kanada',
      by: '',
      pt: 'Canadá',
      es: 'Canadá',
    },
    dial_code: '+1',
    code: 'CA',
    flag: '🇨🇦',
  },
  {
    name: {
      en: 'China',
      ru: 'Китай',
      pl: 'Chiny',
      ua: 'Китай',
      cz: 'Čína',
      by: '',
      pt: 'China',
      es: 'China',
    },
    dial_code: '+86',
    code: 'CN',
    flag: '🇨🇳',
  },
  {
    name: {
      en: 'Christmas Island',
      ru: 'Остров Рождества',
      pl: 'Wyspa Bożego Narodzenia',
      ua: 'Острів Різдва',
      cz: 'Vánoční ostrov',
      by: '',
      pt: 'Ilha do Natal',
      es: 'Isla de Navidad',
    },
    dial_code: '+61',
    code: 'CX',
    flag: '🇨🇽',
  },
  {
    name: {
      en: 'Cocos (Keeling) Islands',
      ru: 'Кокосовые (Килинг) острова',
      pl: 'Wyspy Kokosowe (Keelinga)',
      ua: 'Кокосові (Кілінг) острови',
      cz: 'Kokosové (Keelingovy) ostrovy',
      by: '',
      pt: 'Ilhas dos Cocos',
      es: 'Islas Cocos (Keeling)',
    },
    dial_code: '+61',
    code: 'CC',
    flag: '🇨🇨',
  },
  {
    name: {
      en: 'Colombia',
      ru: 'Колумбия',
      pl: 'Kolumbia',
      ua: 'Колумбія',
      cz: 'Kolumbie',
      by: '',
      pt: 'Colômbia',
      es: 'Colombia',
    },
    dial_code: '+57',
    code: 'CO',
    flag: '🇨🇴',
  },
  {
    name: {
      en: 'Comoros',
      ru: 'Коморские острова',
      pl: 'Komory',
      ua: 'Коморські острови',
      cz: 'Komory',
      by: '',
      pt: 'Comores',
      es: 'Comoras',
    },
    dial_code: '+269',
    code: 'KM',
    flag: '🇰🇲',
  },
  {
    name: {
      en: 'Congo',
      ru: 'Конго',
      pl: 'Kongo',
      ua: 'Конго',
      cz: 'Kongo',
      by: '',
      pt: 'Congo-Brazzaville',
      es: 'Congo',
    },
    dial_code: '+242',
    code: 'CG',
    flag: '🇨🇬',
  },
  {
    name: {
      en: 'Congo, The Democratic Republic of the',
      ru: 'Конго, Демократическая Республика',
      pl: 'Kongo, Republika Demokratyczna',
      ua: 'Конго, Демократична Республіка',
      cz: 'Kongo, Demokratická Republika',
      by: '',
      pt: 'Congo-Kinshasa',
      es: 'Congo, República Democrática del',
    },
    dial_code: '+243',
    code: 'CD',
    flag: '🇨🇩',
  },
  {
    name: {
      en: 'Cook Islands',
      ru: 'Острова Кука',
      pl: 'Wyspy Cooka',
      ua: 'Острови Кука',
      cz: 'Cookovy ostrovy',
      by: '',
      pt: 'Ilhas Cook',
      es: 'Islas Cook',
    },
    dial_code: '+682',
    code: 'CK',
    flag: '🇨🇰',
  },
  {
    name: {
      en: 'Costa Rica',
      ru: 'Коста-Рика',
      pl: 'Kostaryka',
      ua: 'Коста-Ріка',
      cz: 'Kostarika',
      by: '',
      pt: 'Costa Rica',
      es: 'Costa Rica',
    },
    dial_code: '+506',
    code: 'CR',
    flag: '🇨🇷',
  },
  {
    name: {
      en: "Cote d'Ivoire",
      ru: "Кот-д'Ивуар",
      pl: 'Wybrzeże Kości Słoniowej',
      ua: "Кот-д'Івуар",
      cz: 'Pobřeží slonoviny',
      by: '',
      pt: 'Costa do Marfim',
      es: 'Costa de Marfil',
    },
    dial_code: '+225',
    code: 'CI',
    flag: '🇨🇮',
  },
  {
    name: {
      en: 'Croatia',
      ru: 'Хорватия',
      pl: 'Chorwacja',
      ua: 'Хорватія',
      cz: 'Chorvatsko',
      by: '',
      pt: 'Croácia',
      es: 'Croacia',
    },
    dial_code: '+385',
    code: 'HR',
    flag: '🇭🇷',
  },
  {
    name: {
      en: 'Cuba',
      ru: 'Куба',
      pl: 'Kuba',
      ua: 'Куба',
      cz: 'Kuba',
      by: '',
      pt: 'Cuba',
      es: 'Cuba',
    },
    dial_code: '+53',
    code: 'CU',
    flag: '🇨🇺',
  },
  {
    name: {
      en: 'Cyprus',
      ru: 'Кипр',
      pl: 'Cypr',
      ua: 'Кіпр',
      cz: 'Kypr',
      by: '',
      pt: 'Chipre',
      es: 'Chipre',
    },
    dial_code: '+537',
    code: 'CY',
    flag: '🇨🇾',
  },
  {
    name: {
      en: 'Czech Republic',
      ru: 'Чехия',
      pl: 'Republika Czeska',
      ua: 'Чеська Республіка',
      cz: 'Česká republika',
      by: '',
      pt: 'República Checa',
      es: 'República Checa',
    },
    dial_code: '+420',
    code: 'CZ',
    flag: '🇨🇿',
  },
  {
    name: {
      en: 'Denmark',
      ru: 'Дания',
      pl: 'Dania',
      ua: 'Данія',
      cz: 'Dánsko',
      by: '',
      pt: 'Dinamarca',
      es: 'Dinamarca',
    },
    dial_code: '+45',
    code: 'DK',
    flag: '🇩🇰',
  },
  {
    name: {
      en: 'Djibouti',
      ru: 'Джибути',
      pl: 'Dżibuti',
      ua: 'Джибуті',
      cz: 'Džibuti',
      by: '',
      pt: 'Jibuti',
      es: 'Yibuti',
    },
    dial_code: '+253',
    code: 'DJ',
    flag: '🇩🇯',
  },
  {
    name: {
      en: 'Dominica',
      ru: 'Доминика',
      pl: 'Dominika',
      ua: 'Домініка',
      cz: 'Dominika',
      by: '',
      pt: 'Domínica',
      es: 'Dominica',
    },
    dial_code: '+1767',
    code: 'DM',
    flag: '🇩🇲',
  },
  {
    name: {
      en: 'Dominican Republic',
      ru: 'Доминиканская Респблика',
      pl: 'Republika Dominikany',
      ua: 'Домініканська республіка',
      cz: 'Dominikánská republika',
      by: '',
      pt: 'República Dominicana',
      es: 'República Dominicana',
    },
    dial_code: '+1849',
    code: 'DO',
    flag: '🇩🇴',
  },
  {
    name: {
      en: 'Ecuador',
      ru: 'Эквадор',
      pl: 'Ekwador',
      ua: 'Еквадор',
      cz: 'Ekvádor',
      by: '',
      pt: 'Equador',
      es: 'Ecuador',
    },
    dial_code: '+593',
    code: 'EC',
    flag: '🇪🇨',
  },
  {
    name: {
      en: 'Egypt',
      ru: 'Египет',
      pl: 'Egipt',
      ua: 'Єгипет',
      cz: 'Egypt',
      by: '',
      pt: 'Egipto',
      es: 'Egipto',
    },
    dial_code: '+20',
    code: 'EG',
    flag: '🇪🇬',
  },
  {
    name: {
      en: 'El Salvador',
      ru: 'Сальвадор',
      pl: 'Salwador',
      ua: 'Сальвадор',
      cz: 'El Salvador',
      by: '',
      pt: 'Salvador',
      es: 'El Salvador',
    },
    dial_code: '+503',
    code: 'SV',
    flag: '🇸🇻',
  },
  {
    name: {
      en: 'Equatorial Guinea',
      ru: 'Экваториальная Гвинея',
      pl: 'Gwinea Równikowa',
      ua: 'Екваторіальна Гвінея',
      cz: 'Rovníková Guinea',
      by: '',
      pt: 'Guiné Equatorial',
      es: 'Guinea Ecuatorial',
    },
    dial_code: '+240',
    code: 'GQ',
    flag: '🇬🇶',
  },
  {
    name: {
      en: 'Eritrea',
      ru: 'Эритрея',
      pl: 'Erytrea',
      ua: 'Еритрея',
      cz: 'Eritrea',
      by: '',
      pt: 'Eritreia',
      es: 'Eritrea',
    },
    dial_code: '+291',
    code: 'ER',
    flag: '🇪🇷',
  },
  {
    name: {
      en: 'Estonia',
      ru: 'Эстония',
      pl: 'Estonia',
      ua: 'Естонія',
      cz: 'Estonsko',
      by: '',
      pt: 'Estónia',
      es: 'Estonia',
    },
    dial_code: '+372',
    code: 'EE',
    flag: '🇪🇪',
  },
  {
    name: {
      en: 'Ethiopia',
      ru: 'Эфиопия',
      pl: 'Etiopia',
      ua: 'Ефіопія',
      cz: 'Etiopie',
      by: '',
      pt: 'Etiópia',
      es: 'Etiopía',
    },
    dial_code: '+251',
    code: 'ET',
    flag: '🇪🇹',
  },
  {
    name: {
      en: 'Falkland Islands (Malvinas)',
      ru: 'Фолклендские острова (Malvinas)',
      pl: 'Falklandy (Malwiny)',
      ua: 'Фолклендські острови (Мальвінські острови)',
      cz: 'Falklandské ostrovy (Malvíny)',
      by: '',
      pt: 'Ilhas Falkland',
      es: 'Islas Malvinas (Falkland Islands)',
    },
    dial_code: '+500',
    code: 'FK',
    flag: '🇫🇰',
  },
  {
    name: {
      en: 'Faroe Islands',
      ru: 'Фарерские острова',
      pl: 'Wyspy Owcze',
      ua: 'Фарерські острови',
      cz: 'Faerské ostrovy',
      by: '',
      pt: 'Faroé',
      es: 'Islas Feroe',
    },
    dial_code: '+298',
    code: 'FO',
    flag: '🇫🇴',
  },
  {
    name: {
      en: 'Fiji',
      ru: 'Фиджи',
      pl: 'Fidżi',
      ua: 'Фіджі',
      cz: 'Fidži',
      by: '',
      pt: 'Fiji',
      es: 'Fiyi',
    },
    dial_code: '+679',
    code: 'FJ',
    flag: '🇫🇯',
  },
  {
    name: {
      en: 'Finland',
      ru: 'Финляндия',
      pl: 'Finlandia',
      ua: 'Фінляндія',
      cz: 'Finsko',
      by: '',
      pt: 'Finlândia',
      es: 'Finlandia',
    },
    dial_code: '+358',
    code: 'FI',
    flag: '🇫🇮',
  },
  {
    name: {
      en: 'France',
      ru: 'Франция',
      pl: 'Francja',
      ua: 'Франція',
      cz: 'Francie',
      by: '',
      pt: 'França',
      es: 'Francia',
    },
    dial_code: '+33',
    code: 'FR',
    flag: '🇫🇷',
  },
  {
    name: {
      en: 'French Guiana',
      ru: 'Французская Гвиана',
      pl: 'Gujana Francuska',
      ua: 'Французька Гвіана',
      cz: 'Francouzská Guyana',
      by: '',
      pt: 'Guiana Francesa',
      es: 'Guayana Francesa',
    },
    dial_code: '+594',
    code: 'GF',
    flag: '🇬🇫',
  },
  {
    name: {
      en: 'French Polynesia',
      ru: 'Французская Полинезия',
      pl: 'Polinezja Francuska',
      ua: 'Французька Полінезія',
      cz: 'Francouzská Polynésie',
      by: '',
      pt: 'Polinésia Francesa',
      es: 'Polinesia Francesa',
    },
    dial_code: '+689',
    code: 'PF',
    flag: '🇵🇫',
  },
  {
    name: {
      en: 'Gabon',
      ru: 'Габон',
      pl: 'Gabon',
      ua: 'Габон',
      cz: 'Gabon',
      by: '',
      pt: 'Gabão',
      es: 'Gabón',
    },
    dial_code: '+241',
    code: 'GA',
    flag: '🇬🇦',
  },
  {
    name: {
      en: 'Gambia',
      ru: 'Гамбия',
      pl: 'Gambia',
      ua: 'Гамбія',
      cz: 'Gambie',
      by: '',
      pt: 'Gâmbia',
      es: 'Gambia',
    },
    dial_code: '+220',
    code: 'GM',
    flag: '🇬🇲',
  },
  {
    name: {
      en: 'Georgia',
      ru: 'Грузия',
      pl: 'Gruzja',
      ua: 'Грузія',
      cz: 'Gruzie',
      by: '',
      pt: 'Geórgia',
      es: 'Georgia',
    },
    dial_code: '+995',
    code: 'GE',
    flag: '🇬🇪',
  },
  {
    name: {
      en: 'Germany',
      ru: 'Германия',
      pl: 'Niemcy',
      ua: 'Німеччина',
      cz: 'Německo',
      by: '',
      pt: 'Alemanha',
      es: 'Alemania',
    },
    dial_code: '+49',
    code: 'DE',
    flag: '🇩🇪',
  },
  {
    name: {
      en: 'Ghana',
      ru: 'Гана',
      pl: 'Ghana',
      ua: 'Гана',
      cz: 'Ghana',
      by: '',
      pt: 'Gana',
      es: 'Ghana',
    },
    dial_code: '+233',
    code: 'GH',
    flag: '🇬🇭',
  },
  {
    name: {
      en: 'Gibraltar',
      ru: 'Гибралтар',
      pl: 'Gibraltar',
      ua: 'Гібралтар',
      cz: 'Gibraltar',
      by: '',
      pt: 'Gibraltar',
      es: 'Gibraltar',
    },
    dial_code: '+350',
    code: 'GI',
    flag: '🇬🇮',
  },
  {
    name: {
      en: 'Greece',
      ru: 'Греция',
      pl: 'Grecja',
      ua: 'Греція',
      cz: 'Řecko',
      by: '',
      pt: 'Grécia',
      es: 'Grecia',
    },
    dial_code: '+30',
    code: 'GR',
    flag: '🇬🇷',
  },
  {
    name: {
      en: 'Greenland',
      ru: 'Гренландия',
      pl: 'Grenlandia',
      ua: 'Гренландія',
      cz: 'Grenlandia',
      by: '',
      pt: 'Gronelândia',
      es: 'Groenlandia',
    },
    dial_code: '+299',
    code: 'GL',
    flag: '🇬🇱',
  },
  {
    name: {
      en: 'Grenada',
      ru: 'Гренада',
      pl: 'Grenada',
      ua: 'Гренада',
      cz: 'Grenada',
      by: '',
      pt: 'Granada',
      es: 'Granada',
    },
    dial_code: '+1473',
    code: 'GD',
    flag: '🇬🇩',
  },
  {
    name: {
      en: 'Guadeloupe',
      ru: 'Гваделупа',
      pl: 'Gwadelupa',
      ua: 'Гваделупа',
      cz: 'Guadeloupe',
      by: '',
      pt: 'Guadalupe',
      es: 'Guadalupe',
    },
    dial_code: '+590',
    code: 'GP',
    flag: '🇬🇵',
  },
  {
    name: {
      en: 'Guam',
      ru: 'Гуам',
      pl: 'Guam',
      ua: 'Гуам',
      cz: 'Guam',
      by: '',
      pt: 'Guame',
      es: 'Guam',
    },
    dial_code: '+1671',
    code: 'GU',
    flag: '🇬🇺',
  },
  {
    name: {
      en: 'Guatemala',
      ru: 'Гватемала',
      pl: 'Gwatemala',
      ua: 'Гватемала',
      cz: 'Guatemala',
      by: '',
      pt: 'Guatemala',
      es: 'Guatemala',
    },
    dial_code: '+502',
    code: 'GT',
    flag: '🇬🇹',
  },
  {
    name: {
      en: 'Guernsey',
      ru: 'Гернси',
      pl: 'Guernsey',
      ua: 'Гернсі',
      cz: 'Guernsey',
      by: '',
      pt: 'Guernsey',
      es: 'Guernsey',
    },
    dial_code: '+44',
    code: 'GG',
    flag: '🇬🇬',
  },
  {
    name: {
      en: 'Guinea',
      ru: 'Гвинея',
      pl: 'Gwinea',
      ua: 'Гвінея',
      cz: 'Guinea',
      by: '',
      pt: 'Guiné',
      es: 'Guinea',
    },
    dial_code: '+224',
    code: 'GN',
    flag: '🇬🇳',
  },
  {
    name: {
      en: 'Guinea-Bissau',
      ru: 'Гвинея-Бисау',
      pl: 'Gwinea Bissau',
      ua: 'Гвінея-Бісау',
      cz: 'Guinea-Bissau',
      by: '',
      pt: 'Guiné-Bissau',
      es: 'Guinea-Bissau',
    },
    dial_code: '+245',
    code: 'GW',
    flag: '🇬🇼',
  },
  {
    name: {
      en: 'Guyana',
      ru: 'Гайана',
      pl: 'Gujana',
      ua: 'Гайана',
      cz: 'Guyana',
      by: '',
      pt: 'Guiana',
      es: 'Guyana',
    },
    dial_code: '+595',
    code: 'GY',
    flag: '🇬🇾',
  },
  {
    name: {
      en: 'Haiti',
      ru: 'Гаити',
      pl: 'Haiti',
      ua: 'Гаїті',
      cz: 'Haiti',
      by: '',
      pt: 'Haiti',
      es: 'Haití',
    },
    dial_code: '+509',
    code: 'HT',
    flag: '🇭🇹',
  },
  {
    name: {
      en: 'Holy See (Vatican City State)',
      ru: 'Святой Престол (Vatican City State)',
      pl: 'Stolica Apostolska (Państwo Watykańskie)',
      ua: 'Святий Престол (Ватикан)',
      cz: 'Svatý stolec (Vatikánský městský stát)',
      by: '',
      pt: 'Vaticano',
      es: 'Santa Sede (Estado de la Ciudad del Vaticano)',
    },
    dial_code: '+379',
    code: 'VA',
    flag: '🇻🇦',
  },
  {
    name: {
      en: 'Honduras',
      ru: 'Гондурас',
      pl: 'Honduras',
      ua: 'Гондурас',
      cz: 'Honduras',
      by: '',
      pt: 'Honduras',
      es: 'Honduras',
    },
    dial_code: '+504',
    code: 'HN',
    flag: '🇭🇳',
  },
  {
    name: {
      en: 'Hong Kong',
      ru: 'Гонконг',
      pl: 'Hongkong',
      ua: 'Гонконг',
      cz: 'Hongkong',
      by: '',
      pt: 'Hong Kong',
      es: 'Hong Kong',
    },
    dial_code: '+852',
    code: 'HK',
    flag: '🇭🇰',
  },
  {
    name: {
      en: 'Hungary',
      ru: 'Венгрия',
      pl: 'Węgry',
      ua: 'Угорщина',
      cz: 'Maďarsko',
      by: '',
      pt: 'Hungria',
      es: 'Hungría',
    },
    dial_code: '+36',
    code: 'HU',
    flag: '🇭🇺',
  },
  {
    name: {
      en: 'Iceland',
      ru: 'Исландия',
      pl: 'Islandia',
      ua: 'Ісландія',
      cz: 'Island',
      by: '',
      pt: 'Islândia',
      es: 'Islandia',
    },
    dial_code: '+354',
    code: 'IS',
    flag: '🇮🇸',
  },
  {
    name: {
      en: 'India',
      ru: 'Индия',
      pl: 'Indie',
      ua: 'Індія',
      cz: 'Indie',
      by: '',
      pt: 'Índia',
      es: 'India',
    },
    dial_code: '+91',
    code: 'IN',
    flag: '🇮🇳',
  },
  {
    name: {
      en: 'Indonesia',
      ru: 'Индонезия',
      pl: 'Indonezja',
      ua: 'Індонезія',
      cz: 'Indonésie',
      by: '',
      pt: 'Indonésia',
      es: 'Indonesia',
    },
    dial_code: '+62',
    code: 'ID',
    flag: '🇮🇩',
  },
  {
    name: {
      en: 'Iran, Islamic Republic of',
      ru: 'Иран, Исламская Республика',
      pl: 'Iran, Republika Islamska',
      ua: 'Іран, Ісламська Республіка',
      cz: 'Írán, Islámská Republika',
      by: '',
      pt: 'Irão',
      es: 'Irán, República Islámica de',
    },
    dial_code: '+98',
    code: 'IR',
    flag: '🇮🇷',
  },
  {
    name: {
      en: 'Iraq',
      ru: 'Ирак',
      pl: 'Irak',
      ua: 'Ірак',
      cz: 'Irák',
      by: '',
      pt: 'Iraque',
      es: 'Irak',
    },
    dial_code: '+964',
    code: 'IQ',
    flag: '🇮🇶',
  },
  {
    name: {
      en: 'Ireland',
      ru: 'Ирландия',
      pl: 'Irlandia',
      ua: 'Ірландія',
      cz: 'Irsko',
      by: '',
      pt: 'Irlanda',
      es: 'Irlanda',
    },
    dial_code: '+353',
    code: 'IE',
    flag: '🇮🇪',
  },
  {
    name: {
      en: 'Isle of Man',
      ru: 'Остров Мэн',
      pl: 'Wyspa Man',
      ua: 'Острів Мен',
      cz: 'Isle of Man',
      by: '',
      pt: 'Ilha de Man',
      es: 'Isla de Man',
    },
    dial_code: '+44',
    code: 'IM',
    flag: '🇮🇲',
  },
  {
    name: {
      en: 'Israel',
      ru: 'Израиль',
      pl: 'Izrael',
      ua: 'Ізраїль',
      cz: 'Izrael',
      by: '',
      pt: 'Israel',
      es: 'Israel',
    },
    dial_code: '+972',
    code: 'IL',
    flag: '🇮🇱',
  },
  {
    name: {
      en: 'Italy',
      ru: 'Италия',
      pl: 'Włochy',
      ua: 'Італія',
      cz: 'Itálie',
      by: '',
      pt: 'Itália',
      es: 'Italia',
    },
    dial_code: '+39',
    code: 'IT',
    flag: '🇮🇹',
  },
  {
    name: {
      en: 'Jamaica',
      ru: 'Ямайка',
      pl: 'Jamajka',
      ua: 'Ямайка',
      cz: 'Jamaica',
      by: '',
      pt: 'Jamaica',
      es: 'Jamaica',
    },
    dial_code: '+1876',
    code: 'JM',
    flag: '🇯🇲',
  },
  {
    name: {
      en: 'Japan',
      ru: 'Япония',
      pl: 'Japonia',
      ua: 'Японія',
      cz: 'Japonsko',
      by: '',
      pt: 'Japão',
      es: 'Japón',
    },
    dial_code: '+81',
    code: 'JP',
    flag: '🇯🇵',
  },
  {
    name: {
      en: 'Jersey',
      ru: 'Джерси',
      pl: 'Jersey',
      ua: 'Джерсі',
      cz: 'Trikot',
      by: '',
      pt: 'Jersey',
      es: 'Jersey',
    },
    dial_code: '+44',
    code: 'JE',
    flag: '🇯🇪',
  },
  {
    name: {
      en: 'Jordan',
      ru: 'Иордания',
      pl: 'Jordania',
      ua: 'Йорданія',
      cz: 'Jordán',
      by: '',
      pt: 'Jordânia',
      es: 'Jordania',
    },
    dial_code: '+962',
    code: 'JO',
    flag: '🇯🇴',
  },
  {
    name: {
      en: 'Kazakhstan',
      ru: 'Казахстан',
      pl: 'Kazachstan',
      ua: 'Казахстан',
      cz: 'Kazachstán',
      by: '',
      pt: 'Cazaquistão',
      es: 'Kazajstán',
    },
    dial_code: '+77',
    code: 'KZ',
    flag: '🇰🇿',
  },
  {
    name: {
      en: 'Kenya',
      ru: 'Кения',
      pl: 'Kenia',
      ua: 'Кенія',
      cz: 'Keňa',
      by: '',
      pt: 'Quénia',
      es: 'Kenia',
    },
    dial_code: '+254',
    code: 'KE',
    flag: '🇰🇪',
  },
  {
    name: {
      en: 'Kiribati',
      ru: 'Кирибати',
      pl: 'Kiribati',
      ua: 'Kiribati',
      cz: 'Kiribati',
      by: '',
      pt: 'Quiribáti',
      es: 'Kiribati',
    },
    dial_code: '+686',
    code: 'KI',
    flag: '🇰🇮',
  },
  {
    name: {
      en: "Korea, Democratic People's Republic of",
      ru: 'Корея, Народно-Демократическая Республика',
      pl: 'Korea, Republika Ludowo-Demokratyczna',
      ua: 'Корея, Народно-Демократична Республіка',
      cz: 'Korea, Demokratická lidová republika',
      by: '',
      pt: 'Coreia do Norte',
      es: 'Corea, República Popular Democrática de',
    },
    dial_code: '+850',
    code: 'KP',
    flag: '🇰🇵',
  },
  {
    name: {
      en: 'Korea, Republic of',
      ru: 'Республика Корея',
      pl: 'Republika Korei',
      ua: 'Корея, Республіка',
      cz: 'Korea, republika',
      by: '',
      pt: 'Coreia do Sul',
      es: 'Corea, República de',
    },
    dial_code: '+82',
    code: 'KR',
    flag: '🇰🇷',
  },
  {
    name: {
      en: 'Kuwait',
      ru: 'Кувейт',
      pl: 'Kuwejt',
      ua: 'Кувейт',
      cz: 'Kuvajt',
      by: '',
      pt: 'Kuwait',
      es: 'Kuwait',
    },
    dial_code: '+965',
    code: 'KW',
    flag: '🇰🇼',
  },
  {
    name: {
      en: 'Kyrgyzstan',
      ru: 'Kyrgyzstan',
      pl: 'Kirgistan',
      ua: 'Киргизстан',
      cz: 'Kyrgyzstán',
      by: '',
      pt: 'Quirguizistão',
      es: 'Kirguistán',
    },
    dial_code: '+996',
    code: 'KG',
    flag: '🇰🇬',
  },
  {
    name: {
      en: "Lao People's Democratic Republic",
      ru: 'Лаосская Народно-Демократическая Республика',
      pl: 'Laotańska Republika Ludowo-Demokratyczna',
      ua: 'Лаоська Народно-Демократична Республіка',
      cz: 'Laoská lidově demokratická republika',
      by: '',
      pt: 'Laos',
      es: 'República Democrática Popular de Laos',
    },
    dial_code: '+856',
    code: 'LA',
    flag: '🇱🇦',
  },
  {
    name: {
      en: 'Latvia',
      ru: 'Латвия',
      pl: 'Łotwa',
      ua: 'Латвія',
      cz: 'Lotyšsko',
      by: '',
      pt: 'Letónia',
      es: 'Letonia',
    },
    dial_code: '+371',
    code: 'LV',
    flag: '🇱🇻',
  },
  {
    name: {
      en: 'Lebanon',
      ru: 'Ливан',
      pl: 'Liban',
      ua: 'Ліван',
      cz: 'Libanon',
      by: '',
      pt: 'Líbano',
      es: 'Líbano',
    },
    dial_code: '+961',
    code: 'LB',
    flag: '🇱🇧',
  },
  {
    name: {
      en: 'Lesotho',
      ru: 'Лесото',
      pl: 'Lesoto',
      ua: 'Лесото',
      cz: 'Lesotho',
      by: '',
      pt: 'Lesoto',
      es: 'Lesotho',
    },
    dial_code: '+266',
    code: 'LS',
    flag: '🇱🇸',
  },
  {
    name: {
      en: 'Liberia',
      ru: 'Либерия',
      pl: 'Liberia',
      ua: 'Ліберія',
      cz: 'Libérie',
      by: '',
      pt: 'Libéria',
      es: 'Liberia',
    },
    dial_code: '+231',
    code: 'LR',
    flag: '🇱🇷',
  },
  {
    name: {
      en: 'Libyan Arab Jamahiriya',
      ru: 'Ливийская Арабская Джамахирия',
      pl: 'Libijska Arabska Dżamahirija',
      ua: 'Лівійська Арабська Джамахірія',
      cz: 'Libyjský Arab Jamahiriya',
      by: '',
      pt: 'Líbia',
      es: 'Jamahiriya Árabe Libia',
    },
    dial_code: '+218',
    code: 'LY',
    flag: '🇱🇾',
  },
  {
    name: {
      en: 'Liechtenstein',
      ru: 'Лихтенштейн',
      pl: 'Liechtenstein',
      ua: 'Ліхтенштейн',
      cz: 'Lichtenštejnsko',
      by: '',
      pt: 'Listenstaine',
      es: 'Liechtenstein',
    },
    dial_code: '+423',
    code: 'LI',
    flag: '🇱🇮',
  },
  {
    name: {
      en: 'Lithuania',
      ru: 'Литва',
      pl: 'Litwa',
      ua: 'Литва',
      cz: 'Litva',
      by: '',
      pt: 'Lituânia',
      es: 'Lituania',
    },
    dial_code: '+370',
    code: 'LT',
    flag: '🇱🇹',
  },
  {
    name: {
      en: 'Luxembourg',
      ru: 'Люксембург',
      pl: 'Luksemburg',
      ua: 'Люксембург',
      cz: 'Lucembursko',
      by: '',
      pt: 'Luxemburgo',
      es: 'Luxemburgo',
    },
    dial_code: '+352',
    code: 'LU',
    flag: '🇱🇺',
  },
  {
    name: {
      en: 'Macao',
      ru: 'Макао',
      pl: 'Makao',
      ua: 'Макао',
      cz: 'Macao',
      by: '',
      pt: 'Macau',
      es: 'Macao',
    },
    dial_code: '+853',
    code: 'MO',
    flag: '🇲🇴',
  },
  {
    name: {
      en: 'Macedonia, The Former Yugoslav Republic of',
      ru: 'Македония, Бывшая Югославская Республика',
      pl: 'Macedonia, Była Jugosłowiańska Republika',
      ua: 'Македонія, колишня югославська республіка',
      cz: 'Makedonie, Bývalá jugoslávská republika',
      by: '',
      pt: 'Macedónia',
      es: 'Macedonia, Antigua República Yugoslava de',
    },
    dial_code: '+389',
    code: 'MK',
    flag: '🇲🇰',
  },
  {
    name: {
      en: 'Madagascar',
      ru: 'Мадагаскар',
      pl: 'Madagaskar',
      ua: 'Мадагаскар',
      cz: 'Madagaskar',
      by: '',
      pt: 'Madagáscar',
      es: 'Madagascar',
    },
    dial_code: '+261',
    code: 'MG',
    flag: '🇲🇬',
  },
  {
    name: {
      en: 'Malawi',
      ru: 'Малави',
      pl: 'Malawi',
      ua: 'Малаві',
      cz: 'Malawi',
      by: '',
      pt: 'Malávi',
      es: 'Malawi',
    },
    dial_code: '+265',
    code: 'MW',
    flag: '🇲🇼',
  },
  {
    name: {
      en: 'Malaysia',
      ru: 'Малайзия',
      pl: 'Malezja',
      ua: 'Малайзія',
      cz: 'Malajsie',
      by: '',
      pt: 'Malásia',
      es: 'Malasia',
    },
    dial_code: '+60',
    code: 'MY',
    flag: '🇲🇾',
  },
  {
    name: {
      en: 'Maldives',
      ru: 'Мальдивы',
      pl: 'Malediwy',
      ua: 'Мальдіви',
      cz: 'Maledivy',
      by: '',
      pt: 'Maldivas',
      es: 'Maldivas',
    },
    dial_code: '+960',
    code: 'MV',
    flag: '🇲🇻',
  },
  {
    name: {
      en: 'Mexico',
      ru: 'Мексика',
      pl: 'Meksyk',
      ua: 'Мексика',
      cz: 'Mexiko',
      by: '',
      pt: 'México',
      es: 'México',
    },
    dial_code: '+52',
    code: 'MX',
    flag: '🇲🇽',
  },
  {
    name: {
      en: 'Morocco',
      ru: 'Марокко',
      pl: 'Maroko',
      ua: 'Марокко',
      cz: 'Maroko',
      by: '',
      pt: 'Marrocos',
      es: 'Marruecos',
    },
    dial_code: '+212',
    code: 'MA',
    flag: '🇲🇦',
  },
  {
    name: {
      en: 'Myanmar',
      ru: 'Мьянма',
      pl: 'Myanmar',
      ua: "М'янма",
      cz: 'Myanmar',
      by: '',
      pt: 'Birmânia',
      es: 'Myanmar',
    },
    dial_code: '+95',
    code: 'MM',
    flag: '🇲🇲',
  },
  {
    name: {
      en: 'Namibia',
      ru: 'Намибия',
      pl: 'Namibia',
      ua: 'Намібія',
      cz: 'Namibie',
      by: '',
      pt: 'Namíbia',
      es: 'Namibia',
    },
    dial_code: '+264',
    code: 'NA',
    flag: '🇳🇦',
  },
  {
    name: {
      en: 'Nepal',
      ru: 'Непал',
      pl: 'Nepal',
      ua: 'Непал',
      cz: 'Nepál',
      by: '',
      pt: 'Nepal',
      es: 'Nepal',
    },
    dial_code: '+977',
    code: 'NP',
    flag: '🇳🇵',
  },
  {
    name: {
      en: 'Netherlands',
      ru: 'Нидерланды',
      pl: 'Holandia',
      ua: 'Нідерланди',
      cz: 'Holandsko',
      by: '',
      pt: 'Países Baixos',
      es: 'Países Bajos',
    },
    dial_code: '+31',
    code: 'NL',
    flag: '🇳🇱',
  },
  {
    name: {
      en: 'New Caledonia',
      ru: 'Новая Каледония',
      pl: 'Nowa Kaledonia',
      ua: 'Нова Каледонія',
      cz: 'Nová Kaledonie',
      by: '',
      pt: 'Nova Caledónia',
      es: 'Nueva Caledonia',
    },
    dial_code: '+687',
    code: 'NC',
    flag: '🇳🇨',
  },
  {
    name: {
      en: 'New Zealand',
      ru: 'Новая Зеландия',
      pl: 'Nowa Zelandia',
      ua: 'Нова Зеландія',
      cz: 'Nový Zéland',
      by: '',
      pt: 'Nova Zelândia',
      es: 'Nueva Zelanda',
    },
    dial_code: '+64',
    code: 'NZ',
    flag: '🇳🇿',
  },
  {
    name: {
      en: 'Nigeria',
      ru: 'Нигерия',
      pl: 'Nigeria',
      ua: 'Нігерія',
      cz: 'Nigérie',
      by: '',
      pt: 'Nigéria',
      es: 'Nigeria',
    },
    dial_code: '+234',
    code: 'NG',
    flag: '🇳🇬',
  },
  {
    name: {
      en: 'Northern Mariana Islands',
      ru: 'Северные Марианские острова',
      pl: 'Mariany Północne',
      ua: 'Північні Маріанські острови',
      cz: 'Severní Mariany',
      by: '',
      pt: 'Marianas do Norte',
      es: 'Islas Marianas del Norte',
    },
    dial_code: '+1670',
    code: 'MP',
    flag: '🇲🇵',
  },
  {
    name: {
      en: 'Norway',
      ru: 'Норвегия',
      pl: 'Norwegia',
      ua: 'Норвегія',
      cz: 'Norsko',
      by: '',
      pt: 'Noruega',
      es: 'Noruega',
    },
    dial_code: '+47',
    code: 'NO',
    flag: '🇳🇴',
  },
  {
    name: {
      en: 'Oman',
      ru: 'Оман',
      pl: 'Oman',
      ua: 'Оман',
      cz: 'Omán',
      by: '',
      pt: 'Omã',
      es: 'Omán',
    },
    dial_code: '+968',
    code: 'OM',
    flag: '🇴🇲',
  },
  {
    name: {
      en: 'Pakistan',
      ru: 'Пакистан',
      pl: 'Pakistan',
      ua: 'Пакистан',
      cz: 'Pákistán',
      by: '',
      pt: 'Paquistão',
      es: 'Pakistán',
    },
    dial_code: '+92',
    code: 'PK',
    flag: '🇵🇰',
  },
  {
    name: {
      en: 'Philippines',
      ru: 'Филиппины',
      pl: 'Filipiny',
      ua: 'Філіппіни',
      cz: 'Filipíny',
      by: '',
      pt: 'Filipinas',
      es: 'Filipinas',
    },
    dial_code: '+63',
    code: 'PH',
    flag: '🇵🇭',
  },
  {
    name: {
      en: 'Poland',
      ru: 'Польша',
      pl: 'Polska',
      ua: 'Польща',
      cz: 'Polsko',
      by: '',
      pt: 'Polónia',
      es: 'Polonia',
    },
    dial_code: '+48',
    code: 'PL',
    flag: '🇵🇱',
  },
  {
    name: {
      en: 'Portugal',
      ru: 'Португалия',
      pl: 'Portugalia',
      ua: 'Португалія',
      cz: 'Portugalsko',
      by: '',
      pt: 'Portugal',
      es: 'Portugal',
    },
    dial_code: '+351',
    code: 'PT',
    flag: '🇵🇹',
  },
  {
    name: {
      en: 'Qatar',
      ru: 'Катар',
      pl: 'Katar',
      ua: 'Катар',
      cz: 'Katar',
      by: '',
      pt: 'Catar',
      es: 'Qatar',
    },
    dial_code: '+974',
    code: 'QA',
    flag: '🇶🇦',
  },
  {
    name: {
      en: 'Romania',
      ru: 'Румыния',
      pl: 'Rumunia',
      ua: 'Румунія',
      cz: 'Rumunsko',
      by: '',
      pt: 'Roménia',
      es: 'Rumanía',
    },
    dial_code: '+40',
    code: 'RO',
    flag: '🇷🇴',
  },
  {
    name: {
      en: 'Russia',
      ru: 'Россия',
      pl: 'Rosja',
      ua: 'Росія',
      cz: 'Rusko',
      by: '',
      pt: 'Rússia',
      es: 'Rusia',
    },
    dial_code: '+7',
    code: 'RU',
    flag: '🇷🇺',
  },
  {
    name: {
      en: 'Rwanda',
      ru: 'Руанда',
      pl: 'Rwanda',
      ua: 'Руанда',
      cz: 'Rwanda',
      by: '',
      pt: 'Ruanda',
      es: 'Ruanda',
    },
    dial_code: '+250',
    code: 'RW',
    flag: '🇷🇼',
  },
  {
    name: {
      en: 'Réunion',
      ru: 'Реюньон',
      pl: 'Réunion',
      ua: 'Реюньйон',
      cz: 'Réunion',
      by: '',
      pt: 'Reunião',
      es: 'Reunión',
    },
    dial_code: '+262',
    code: 'RE',
    flag: '🇷🇪',
  },
  {
    name: {
      en: 'Saudi Arabia',
      ru: 'Саудовская Аравия',
      pl: 'Arabia Saudyjska',
      ua: 'Саудівська Аравія',
      cz: 'Saudská arábie',
      by: '',
      pt: 'Arábia Saudita',
      es: 'San Vicente y las Granadinas',
    },
    dial_code: '+966',
    code: 'SA',
    flag: '🇸🇦',
  },
  {
    name: {
      en: 'Serbia',
      ru: 'Сербия',
      pl: 'Serbia',
      ua: 'Сербія',
      cz: 'Srbsko',
      by: '',
      pt: 'Sérvia',
      es: 'Serbia',
    },
    dial_code: '+381',
    code: 'RS',
    flag: '🇷🇸',
  },
  {
    name: {
      en: 'Singapore',
      ru: 'Сингапур',
      pl: 'Singapur',
      ua: 'Сінгапур',
      cz: 'Singapur',
      by: '',
      pt: 'Singapura',
      es: 'Singapur',
    },
    dial_code: '+65',
    code: 'SG',
    flag: '🇸🇬',
  },
  {
    name: {
      en: 'Slovakia',
      ru: 'Словакия',
      pl: 'Słowacja',
      ua: 'Словаччина',
      cz: 'Slovensko',
      by: '',
      pt: 'Eslováquia',
      es: 'Eslovaquia',
    },
    dial_code: '+421',
    code: 'SK',
    flag: '🇸🇰',
  },
  {
    name: {
      en: 'Slovenia',
      ru: 'Словения',
      pl: 'Słowenia',
      ua: 'Словенія',
      cz: 'Slovinsko',
      by: '',
      pt: 'Eslovénia',
      es: 'Eslovenia',
    },
    dial_code: '+386',
    code: 'SI',
    flag: '🇸🇮',
  },
  {
    name: {
      en: 'South Africa',
      ru: 'Южная Африка',
      pl: 'Afryka Południowa',
      ua: 'Південна Африка',
      cz: 'Jižní Afrika',
      by: '',
      pt: 'África do Sul',
      es: 'Sudáfrica',
    },
    dial_code: '+27',
    code: 'ZA',
    flag: '🇿🇦',
  },
  {
    name: {
      en: 'Spain',
      ru: 'Испания',
      pl: 'Hiszpania',
      ua: 'Іспанія',
      cz: 'Španělsko',
      by: '',
      pt: 'Espanha',
      es: 'España',
    },
    dial_code: '+34',
    code: 'ES',
    flag: '🇪🇸',
  },
  {
    name: {
      en: 'Sri Lanka',
      ru: 'Шри-Ланка',
      pl: 'Sri Lanka',
      ua: 'Шрі Ланка',
      cz: 'Srí Lanka',
      by: '',
      pt: 'Sri Lanca',
      es: 'Sri Lanka',
    },
    dial_code: '+94',
    code: 'LK',
    flag: '🇱🇰',
  },
  {
    name: {
      en: 'Sudan',
      ru: 'Судан',
      pl: 'Sudan',
      ua: 'Судан',
      cz: 'Súdán',
      by: '',
      pt: 'Sudão',
      es: 'Sudán',
    },
    dial_code: '+249',
    code: 'SD',
    flag: '🇸🇩',
  },
  {
    name: {
      en: 'Sweden',
      ru: 'Швеция',
      pl: 'Szwecja',
      ua: 'Швеція',
      cz: 'Švédsko',
      by: '',
      pt: 'Suécia',
      es: 'Suecia',
    },
    dial_code: '+46',
    code: 'SE',
    flag: '🇸🇪',
  },
  {
    name: {
      en: 'Switzerland',
      ru: 'Швейцария',
      pl: 'Szwajcaria',
      ua: 'Швейцарія',
      cz: 'Švýcarsko',
      by: '',
      pt: 'Suíça',
      es: 'Suiza',
    },
    dial_code: '+41',
    code: 'CH',
    flag: '🇨🇭',
  },
  {
    name: {
      en: 'Syrian Arab Republic',
      ru: 'Сирийская Арабская Республика',
      pl: 'Republika Syryjsko-Arabska',
      ua: 'Сирійська Арабська Республіка',
      cz: 'Syrská Arabská republika',
      by: '',
      pt: 'Síria',
      es: 'República Árabe Siria',
    },
    dial_code: '+963',
    code: 'SY',
    flag: '🇸🇾',
  },
  {
    name: {
      en: 'Taiwan, Province of China',
      ru: 'Тайвань, провинция Китая',
      pl: 'Tajwan, prowincja Chin',
      ua: 'Тайвань, провінція Китаю',
      cz: 'Tchaj-wan, provincie Číny',
      by: '',
      pt: 'Taiwan',
      es: 'Taiwán, provincia de China',
    },
    dial_code: '+886',
    code: 'TW',
    flag: '🇹🇼',
  },
  {
    name: {
      en: 'Tajikistan',
      ru: 'Таджикистан',
      pl: 'Tadżykistan',
      ua: 'Таджикистан',
      cz: 'Tádžikistán',
      by: '',
      pt: 'Tajiquistão',
      es: 'Tayikistán',
    },
    dial_code: '+992',
    code: 'TJ',
    flag: '🇹🇯',
  },
  {
    name: {
      en: 'Thailand',
      ru: 'Таиланд',
      pl: 'Tajlandia',
      ua: 'Таїланд',
      cz: 'Thajsko',
      by: '',
      pt: 'Tailândia',
      es: 'Tailandia',
    },
    dial_code: '+66',
    code: 'TH',
    flag: '🇹🇭',
  },
  {
    name: {
      en: 'Ukraine',
      ru: 'Украина',
      pl: 'Ukraina',
      ua: 'Україна',
      cz: 'Ukrajina',
      by: '',
      pt: 'Ucrânia',
      es: 'Ucrania',
    },
    dial_code: '+380',
    code: 'UA',
    flag: '🇺🇦',
  },
  {
    name: {
      en: 'United Arab Emirates',
      ru: 'Объединенные Арабские Эмираты',
      pl: 'Zjednoczone Emiraty Arabskie',
      ua: "Об'єднані Арабські Емірати",
      cz: 'Spojené arabské emiráty',
      by: '',
      pt: 'Emiratos Árabes Unidos',
      es: 'Emiratos Árabes Unidos',
    },
    dial_code: '+971',
    code: 'AE',
    flag: '🇦🇪',
  },
  {
    name: {
      en: 'United Kingdom',
      ru: 'Объединенное Королевство',
      pl: 'Zjednoczone Królestwo',
      ua: "Об'єднане Королівство",
      cz: 'Spojené království',
      by: '',
      pt: 'Reino Unido',
      es: 'Reino Unido',
    },
    dial_code: '+44',
    code: 'GB',
    flag: '🇬🇧',
  },
  {
    name: {
      en: 'United States',
      ru: 'Соединенные Штаты',
      pl: 'Stany Zjednoczone',
      ua: 'Сполучені Штати',
      cz: 'Spojené státy',
      by: '',
      pt: 'Estados Unidos',
      es: 'Estados Unidos',
    },
    dial_code: '+1',
    code: 'US',
    flag: '🇺🇸',
  },
  {
    name: {
      en: 'Uzbekistan',
      ru: 'Узбекистан',
      pl: 'Uzbekistan',
      ua: 'Узбекистан',
      cz: 'Uzbekistán',
      by: '',
      pt: 'Usbequistão',
      es: 'Uzbekistán',
    },
    dial_code: '+998',
    code: 'UZ',
    flag: '🇺🇿',
  },
  {
    name: {
      en: 'Viet Nam',
      ru: 'Вьетнам',
      pl: 'Wietnam',
      ua: "В'єтнам",
      cz: 'Vietnam',
      by: '',
      pt: 'Vietname',
      es: 'Vietnam',
    },
    dial_code: '+84',
    code: 'VN',
    flag: '🇻🇳',
  },
  {
    name: {
      en: 'Yemen',
      ru: 'Йемен',
      pl: 'Jemen',
      ua: 'Ємен',
      cz: 'Jemen',
      by: '',
      pt: 'Iémen',
      es: 'Yemen',
    },
    dial_code: '+967',
    code: 'YE',
    flag: '🇾🇪',
  },
  {
    name: {
      en: 'Zimbabwe',
      ru: 'Зимбабве',
      pl: 'Zimbabwe',
      ua: 'Зімбабве',
      cz: 'Zimbabwe',
      by: '',
      pt: 'Zimbabué',
      es: 'Zimbabue',
    },
    dial_code: '+263',
    code: 'ZW',
    flag: '🇿🇼',
  },
];
