export default {
  search: require('../assets/images/search.png'),
  eyeIcon: require('../assets/images/EyeIcon.png'),
  eyeClosed: require('../assets/images/eyeClosed.png'),
  deleteIcon: require('../assets/images/DeleteIcon.png'),
  cancelIcon: require('../assets/images/cancel_Icon.png'),
  warningIcon: require('../assets/images/warningBG.png'),
  circleIcon: require('../assets/images/circle_Info.png'),
  bottomArrow: require('../assets/images/Arrow_Bottom.png'),
  calenderIcon: require('../assets/images/Calendar_icon1.png'),
  profileTypeImg: require('../assets/images/profile_type.png'),
  cancelJobIcon: require('../assets/images/Cancel_job_icon.png'),
  businessClient: require('../assets/images/business_client.png'),
  radioButton: require('../assets/images/RadioButton_Inactive.png'),
  leftArrow: require('../assets/images/arrow-left(non-optimized).png'),
  staffWorker: require('../assets/images/staff_worker_unselected.png'),
  radioButtonActive: require('../assets/images/RadioButton_Active.png'),
  confirmationCheck: require('../assets/images/ConfirmationCheckIcon.png'),
  jobRadioButtonActive: require('../assets/images/RadioButton_Active.png'),
  staffWorkerSelected: require('../assets/images/staff_worker_selected.png'),
  jobRadioButtonInActive: require('../assets/images/RadioButton_Inactive.png'),
  businessClientSelected: require('../assets/images/Business_Client_Selected.png'),
};
